/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-EJJKwKvQ9hOKV1r2w6Z-eMCfJ2x471lL8U2tyxZ-PN-OONZst851iNnH6T6u-An-hbtadXUQ8xesr8yjq2r7OKMr-ZqKd9qIaMQ0aDF6rbAAmlIJHP81G-7H",
  "tt": "tt-1-l0mCwTvuEyhAMB8HK-XjqFqF0OBgU5BxsOJ3Gf6Wxgg=",
  "version": "2020-11-20"
}

export default ebconfig;